In [42]:
import numpy as np
from Data.common.gradient import numerical_gradient

def function_2(x):
    return x[0] ** 2 + x[1] ** 2

In [43]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x

    for i in range(step_num):
        grad = numerical_gradient(f, x)
        x -= lr * grad

    return x

In [44]:
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=0.1, step_num=100)

array([-6.11110793e-10,  8.14814391e-10])

In [45]:
# High Learning Rate (lr = 10.0)
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=10.0, step_num=100)

array([-2.58983747e+13, -1.29524862e+12])

In [46]:
# Low Learning Rate (lr = 1e-10)
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=1e-10, step_num=100)

array([-2.99999994,  3.99999992])

The Gradient of Neural Network

In [47]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from Data.common.functions import softmax, cross_entropy_error
from Data.common.gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [48]:
net = simpleNet()
print(net.W)

[[ 0.02644858  0.11253931 -0.39941413]
 [ 1.25478259 -1.07534845  0.71905116]]


In [49]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[ 1.14517348 -0.90029002  0.40749756]


In [50]:
print(np.argmax(p))

0


In [51]:
t = np.array([0, 0, 1])
print(net.loss(x, t))

1.212383312001211


In [52]:
x = np.array([0.6, 0.9])
t = np.array([0, 0, 1])

net = simpleNet()

f = lambda w: net.loss(x, t)
dW = numerical_gradient(f, net.W)

print(dW)

IndexError: index 2 is out of bounds for axis 0 with size 2