In [1]:
import numpy as np
from Data.common.gradient import numerical_gradient

def function_2(x):
    return x[0] ** 2 + x[1] ** 2

In [2]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x

    for i in range(step_num):
        grad = numerical_gradient(f, x)
        x -= lr * grad

    return x

In [3]:
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=0.1, step_num=100)

array([-6.11110793e-10,  8.14814391e-10])

In [4]:
# High Learning Rate (lr = 10.0)
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=10.0, step_num=100)

array([-2.58983747e+13, -1.29524862e+12])

In [5]:
# Low Learning Rate (lr = 1e-10)
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=1e-10, step_num=100)

array([-2.99999994,  3.99999992])

The Gradient of Neural Network

In [6]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from Data.common.functions import softmax, cross_entropy_error
from Data.common.gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [7]:
net = simpleNet()
print(net.W)

[[-1.57191129  0.22411406  0.12781916]
 [-2.65176056  0.51783937 -1.64019894]]


In [8]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[-3.32973127  0.60052387 -1.39948755]


In [9]:
print(np.argmax(p))

1


In [10]:
t = np.array([0, 0, 1])
print(net.loss(x, t))

2.1440870121855853


In [11]:
x = np.array([0.6, 0.9])
t = np.array([0, 0, 1])

net = simpleNet()

f = lambda w: net.loss(x, t)
dW = numerical_gradient(f, net.W)

print(dW)

[[ 0.04945011  0.23667536 -0.28612547]
 [ 0.07417517  0.35501303 -0.4291882 ]]
