In [8]:
import numpy as np

Multidimensional array

In [9]:
A = np.array([1, 2, 3, 4])

print(A)
A 

[1 2 3 4]


array([1, 2, 3, 4])

In [10]:
np.ndim(A)

1

In [11]:
A.shape

(4,)

In [12]:
A.shape[0]

4

In [13]:
B = np.array([[1, 2], [3, 4], [5, 6]])

print(B)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
np.ndim(B)

2

In [15]:
B.shape

(3, 2)

Matrix multiplication

In [16]:
A = np.array([[1, 2], [3, 4]])
A.shape

(2, 2)

In [17]:
B = np.array([[5, 6], [7, 8]])
B.shape

(2, 2)

In [18]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [19]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

In [20]:
B = np.array([[1, 2], [3, 4], [5, 6]])
B.shape

(3, 2)

In [21]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [22]:
C = np.array([[1, 2], [3, 4]])
C.shape

(2, 2)

In [23]:
A.shape

(2, 3)

In [24]:
np.dot(A, C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [25]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A.shape

(3, 2)

In [26]:
B = np.array([7, 8])
B.shape

(2,)

In [27]:
np.dot(A, B)

array([23, 53, 83])

Dot product in Neural Networks

In [28]:
X = np.array([1, 2])
X.shape

(2,)

In [31]:
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)
W.shape

[[1 3 5]
 [2 4 6]]


(2, 3)

In [32]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
