Softmax function

In [1]:
import numpy as np

In [2]:
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [3]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [4]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [5]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

print(softmax(a))

[0.01821127 0.24519181 0.73659691]


Enhanced softmax function

In [8]:
a = np.array([1010, 1000, 990])

print(softmax(a))
print(np.exp(a) / np.sum(np.exp(a)))

[nan nan nan]
[nan nan nan]


C:\Users\xingc\AppData\Local\Temp\ipykernel_15352\4279793493.py:2: RuntimeWarning: overflow encountered in exp
  exp_a = np.exp(a)
C:\Users\xingc\AppData\Local\Temp\ipykernel_15352\4279793493.py:4: RuntimeWarning: invalid value encountered in divide
  y = exp_a / sum_exp_a
C:\Users\xingc\AppData\Local\Temp\ipykernel_15352\1771570435.py:4: RuntimeWarning: overflow encountered in exp
  print(np.exp(a) / np.sum(np.exp(a)))


In [9]:
c = np.max(a)
print(a - c)
print(np.exp(a - c) / np.sum(np.exp(a - c)))

[  0 -10 -20]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]


In [10]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

print(softmax(a))

[9.99954600e-01 4.53978686e-05 2.06106005e-09]


In [11]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)
print(np.sum(y))

[0.01821127 0.24519181 0.73659691]
1.0
